
INFO 	2016-06-02 18:00:32 	[configuration] 	script to access/write from/to metadata: /users/project/4DGenome/utils/io_metadata.sh
INFO 	2016-06-02 18:00:32 	[configuration] 	metadata database: /users/project/4DGenome/data/4DGenome_metadata.db
INFO 	2016-06-02 18:00:32 	[configuration] 	data for 66950b082_c478f1d09 will be stored at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09
INFO 	2016-06-02 18:00:32 	[configuration] 	paths to input FASTQ files extracted from the metadata
INFO 	2016-06-02 18:01:03 	[configuration] 	species (Homo_sapiens) and assembly version (hg38_mmtv) extracted from the metadata
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 100, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE hic SET "QUEUE"=? WHERE hic."SAMPLE_ID" = ?'] [parameters: ('long-sl65', '66950b082_c478f1d09')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "MEMORY"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('100G', '66950b082_c478f1d09;2016-06-02-18-00')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 100, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE hic SET "SLOTS"=? WHERE hic."SAMPLE_ID" = ?'] [parameters: ('10', '66950b082_c478f1d09')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "ASSEMBLY_VERSION"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('hg38_mmtv', '66950b082_c478f1d09;2016-06-02-18-00')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "JOB_NAME"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('hic-16.05', '66950b082_c478f1d09;2016-06-02-18-00')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 100, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE hic SET "PATH_JOB_FILE"=? WHERE hic."SAMPLE_ID" = ?'] [parameters: ('/users/project/4DGenome/pipelines/hic-16.05/job_cmd/job_66950b082_c478f1d09_2016_06_02_full_hic-16.05.sh', '66950b082_c478f1d09')]

INFO 	2016-06-02 18:02:48 	[preliminary_checks] 	66950b082_c478f1d09 found in /users/project/4DGenome/data/4DGenome_metadata.db
INFO 	2016-06-02 18:17:37 	[preliminary_checks] 	paths to read1 and read2 saved to metadata database
INFO 	2016-06-02 18:17:38 	[preliminary_checks] 	Sequencing index added as part of the metadata agrees with that observed in the FASTQ file
INFO 	2016-06-02 18:17:40 	[preliminary_checks] 	read length added as part of the metadata agrees with that observed in the FASTQ file
INFO 	2016-06-02 18:17:40 	[preliminary_checks] 	genome reference FASTA file found at /users/GR/mb/jquilez/assemblies/homo_sapiens/hg38_mmtv/ucsc/hg38_mmtv_chr1-22XYM.fa
INFO 	2016-06-02 18:17:55 	[preliminary_checks] 	paths to reference FASTA saved to metadata database
TIME 	2016-06-02 18:17:55 	[preliminary_checks] 	step time for completion (seconds) = 908

INFO 	2016-06-02 18:17:57 	[raw_fastqs_quality_plots] 	restriction enzyme = DpnII
INFO 	2016-06-02 18:17:57 	[raw_fastqs_quality_plots] 	a subset of 100000 reds will be used to generate the quality plots
INFO 	2016-06-02 18:17:57 	[raw_fastqs_quality_plots] 	making quality plots of the raw FASTQ files... plots saved at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/plots/hg38_mmtv/raw_fastqs_quality_plots
INFO 	2016-06-02 18:18:14 	[raw_fastqs_quality_plots] 	percentages of dangling ends and ligated sites in read1 and read2 saved to metadata database
TIME 	2016-06-02 18:18:14 	[raw_fastqs_quality_plots] 	step time for completion (seconds) = 17

INFO 	2016-06-02 18:18:16 	[trim_reads_trimmomatic] 	sequencing type = PE
INFO 	2016-06-02 18:18:16 	[trim_reads_trimmomatic] 	trimming TruSeq3 adapter sequences for HiSeq, NextSeq or HiSeq
INFO 	2016-06-02 18:18:16 	[trim_reads_trimmomatic] 	trimming low-quality reads ends using trimmomatic's recommended practices
INFO 	2016-06-02 19:57:20 	[trim_reads_trimmomatic] 	parse step log to extract generated metadata
INFO 	2016-06-02 19:57:20 	[trim_reads_trimmomatic] 	reads after trimming = 200741041
INFO 	2016-06-02 19:57:52 	[trim_reads_trimmomatic] 	trimmomatic parameters and numbe of trimmed reads added to metadata
INFO 	2016-06-02 19:57:52 	[trim_reads_trimmomatic] 	trimmed reads are in /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/fastqs_processed/trimmomatic/paired_end
INFO 	2016-06-02 19:57:52 	[trim_reads_trimmomatic] 	unpaired reads are deleted
TIME 	2016-06-02 19:57:52 	[trim_reads_trimmomatic] 	step time for completion (seconds) = 5976

INFO 	2016-06-02 19:57:53 	[align_and_merge] 	species = Homo_sapiens
INFO 	2016-06-02 19:57:53 	[align_and_merge] 	assembly version = hg38_mmtv
INFO 	2016-06-02 19:57:53 	[align_and_merge] 	restriction enzyme = DpnII
INFO 	2016-06-02 19:57:53 	[align_and_merge] 	read length = 75
INFO 	2016-06-02 19:57:53 	[align_and_merge] 	genome reference FASTA file found at /users/GR/mb/jquilez/assemblies/homo_sapiens/hg38_mmtv/ucsc/hg38_mmtv_chr1-22XYM.fa
INFO 	2016-06-02 19:57:53 	[align_and_merge] 	mapping, processing reads according to restriction enzyme fragments and merging aligments for read1 and read2...
INFO 	2016-06-03 06:39:36 	[align_and_merge] 	output saved in /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/logs/hg38_mmtv/66950b082_c478f1d09_align_and_merge_paired_end.log
TIME 	2016-06-03 06:44:03 	[align_and_merge] 	step time for completion (seconds) = 38770

INFO 	2016-06-03 06:44:19 	[post_mapping_statistics] 	generating post mapping descriptive statistics plots...
INFO 	2016-06-03 07:31:14 	[post_mapping_statistics] 	fraction of reads mapped read1 = 0.965798727725
INFO 	2016-06-03 07:31:14 	[post_mapping_statistics] 	fraction of reads mapped read2 = 0.949807822308
INFO 	2016-06-03 07:31:14 	[post_mapping_statistics] 	number of pairs in which both read1 and read2 are mapped = 151559455
INFO 	2016-06-03 07:31:14 	[post_mapping_statistics] 	counts-to-distance slope = -1.19805779632
TIME 	2016-06-03 07:31:32 	[post_mapping_statistics] 	step time for completion (seconds) = 2833

INFO 	2016-06-03 07:32:00 	[reads_filtering] 	filtering reads based on multiple quality parameters...
INFO 	2016-06-03 07:32:00 	[reads_filtering] 	filtered reads to be used for subsequent analyses are at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/results/hg38_mmtv/filtered_reads
INFO 	2016-06-03 07:32:00 	[reads_filtering] 	excluded reads due to dangling ends are at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/results/hg38_mmtv/excluded_reads/dangling_ends
INFO 	2016-06-03 07:32:00 	[reads_filtering] 	excluded reads due to self circle are at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/results/hg38_mmtv/excluded_reads/self_circle
INFO 	2016-06-03 07:32:00 	[reads_filtering] 	summary of excluded reads at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/results/hg38_mmtv/excluded_reads/summary_excluded_per_filter
INFO 	2016-06-03 08:00:53 	[reads_filtering] 	numbers and fractions of filtered and excluded reads added to the metadata
TIME 	2016-06-03 08:03:21 	[reads_filtering] 	step time for completion (seconds) = 1908

INFO 	2016-06-03 08:03:23 	[post_filtering_statistics] 	generating post filtering descriptive statistics plots... saved at /users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/plots/hg38_mmtv/post_filtering_statistics:
INFO 	2016-06-03 08:03:23 	[post_filtering_statistics] 	- filtered reads: sequencing coverage along chromosomes, coverage values and interaction matrix
INFO 	2016-06-03 08:03:23 	[post_filtering_statistics] 	- dangling ends: sequencing coverage along chromosomes and coverage values
INFO 	2016-06-03 08:03:23 	[post_filtering_statistics] 	- self-circle ends: sequencing coverage along chromosomes and coverage values
TIME 	2016-06-03 08:27:04 	[post_filtering_statistics] 	step time for completion (seconds) = 1421

INFO 	2016-06-03 08:27:15 	[map_to_bam] 	converting MAP to BAM
[bam_sort_core] merging from 100 files...
TIME 	2016-06-03 10:43:02 	[map_to_bam] 	step time for completion (seconds) = 8147

INFO 	2016-06-03 10:43:13 	[downstream_bam] 	perform several downstream analyses
INFO 	2016-06-03 17:42:05 	[downstream_bam] 	number of TADs = 2869
TIME 	2016-06-03 17:42:37 	[downstream_bam] 	step time for completion (seconds) = 25164

INFO 	2016-06-03 17:42:38 	[clean_up] 	deleting the following intermediate files/directories:
INFO 	2016-06-03 17:42:38 	[clean_up] 	/users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/fastqs_processed
INFO 	2016-06-03 17:42:38 	[clean_up] 	/users/project/4DGenome_no_backup/data/hic/samples/66950b082_c478f1d09/mapped_reads
TIME 	2016-06-03 17:42:39 	[clean_up] 	step time for completion (seconds) = 1


INFO 	2016-06-03 17:42:40 	[pipeline] 	completed successfully
TIME 	2016-06-03 17:42:40 	[pipeline] 	total time for completion (seconds) = 85328

