Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 77, in emit
    self.doRollover()
  File "/usr/lib64/python2.6/logging/handlers.py", line 121, in doRollover
    self.stream.close()
IOError: [Errno 116] Stale file handle
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1524, in shutdown
    h.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 770, in flush
    self.stream.flush()
ValueError: I/O operation on closed file
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1524, in shutdown
    h.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 770, in flush
    self.stream.flush()
ValueError: I/O operation on closed file

INFO 	2016-06-02 18:00:32 	[configuration] 	script to access/write from/to metadata: /users/project/4DGenome/utils/io_metadata.sh
INFO 	2016-06-02 18:00:32 	[configuration] 	metadata database: /users/project/4DGenome/data/4DGenome_metadata.db
INFO 	2016-06-02 18:00:32 	[configuration] 	data for dc3a1e069_51720e9cf will be stored at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf
INFO 	2016-06-02 18:00:32 	[configuration] 	paths to input FASTQ files extracted from the metadata
INFO 	2016-06-02 18:01:00 	[configuration] 	species (Homo_sapiens) and assembly version (hg38_mmtv) extracted from the metadata
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "QUEUE"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('long-sl65', 'dc3a1e069_51720e9cf;2016-06-02-18-00')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "MAX_TIME"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('100:00:00', 'dc3a1e069_51720e9cf;2016-06-02-18-00')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 100, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE hic SET "SLOTS"=? WHERE hic."SAMPLE_ID" = ?'] [parameters: ('10', 'dc3a1e069_51720e9cf')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "ASSEMBLY_VERSION"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('hg38_mmtv', 'dc3a1e069_51720e9cf;2016-06-02-18-00')]
Traceback (most recent call last):
  File "/users/project/4DGenome/utils/io_metadata.py", line 107, in <module>
    tab.upsert(new_data, ['JOB_ID'])
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 171, in upsert
    row_count = self.update(row, keys, ensure=ensure, types=types)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/dataset/persistence/table.py", line 144, in update
    rp = self.database.executable.execute(stmt)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/software/mb/el6.3/Conda/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'UPDATE jobs SET "JOB_NAME"=? WHERE jobs."JOB_ID" = ?'] [parameters: ('hic-16.05', 'dc3a1e069_51720e9cf;2016-06-02-18-00')]

INFO 	2016-06-02 18:02:49 	[preliminary_checks] 	dc3a1e069_51720e9cf found in /users/project/4DGenome/data/4DGenome_metadata.db
INFO 	2016-06-02 18:11:49 	[preliminary_checks] 	paths to read1 and read2 saved to metadata database
INFO 	2016-06-02 18:11:51 	[preliminary_checks] 	Sequencing index added as part of the metadata agrees with that observed in the FASTQ file
INFO 	2016-06-02 18:11:52 	[preliminary_checks] 	read length added as part of the metadata agrees with that observed in the FASTQ file
INFO 	2016-06-02 18:11:52 	[preliminary_checks] 	genome reference FASTA file found at /users/GR/mb/jquilez/assemblies/homo_sapiens/hg38_mmtv/ucsc/hg38_mmtv_chr1-22XYM.fa
INFO 	2016-06-02 18:12:22 	[preliminary_checks] 	paths to reference FASTA saved to metadata database
TIME 	2016-06-02 18:12:22 	[preliminary_checks] 	step time for completion (seconds) = 575

INFO 	2016-06-02 18:12:24 	[raw_fastqs_quality_plots] 	restriction enzyme = DpnII
INFO 	2016-06-02 18:12:24 	[raw_fastqs_quality_plots] 	a subset of 100000 reds will be used to generate the quality plots
INFO 	2016-06-02 18:12:24 	[raw_fastqs_quality_plots] 	making quality plots of the raw FASTQ files... plots saved at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/plots/hg38_mmtv/raw_fastqs_quality_plots
INFO 	2016-06-02 18:12:44 	[raw_fastqs_quality_plots] 	percentages of dangling ends and ligated sites in read1 and read2 saved to metadata database
TIME 	2016-06-02 18:12:44 	[raw_fastqs_quality_plots] 	step time for completion (seconds) = 20

INFO 	2016-06-02 18:12:45 	[trim_reads_trimmomatic] 	sequencing type = PE
INFO 	2016-06-02 18:12:45 	[trim_reads_trimmomatic] 	trimming TruSeq3 adapter sequences for HiSeq, NextSeq or HiSeq
INFO 	2016-06-02 18:12:45 	[trim_reads_trimmomatic] 	trimming low-quality reads ends using trimmomatic's recommended practices
INFO 	2016-06-02 19:13:59 	[trim_reads_trimmomatic] 	parse step log to extract generated metadata
INFO 	2016-06-02 19:13:59 	[trim_reads_trimmomatic] 	reads after trimming = 123454784
INFO 	2016-06-02 19:14:33 	[trim_reads_trimmomatic] 	trimmomatic parameters and numbe of trimmed reads added to metadata
INFO 	2016-06-02 19:14:33 	[trim_reads_trimmomatic] 	trimmed reads are in /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/fastqs_processed/trimmomatic/paired_end
INFO 	2016-06-02 19:14:33 	[trim_reads_trimmomatic] 	unpaired reads are deleted
TIME 	2016-06-02 19:14:34 	[trim_reads_trimmomatic] 	step time for completion (seconds) = 3709

INFO 	2016-06-02 19:14:35 	[align_and_merge] 	species = Homo_sapiens
INFO 	2016-06-02 19:14:35 	[align_and_merge] 	assembly version = hg38_mmtv
INFO 	2016-06-02 19:14:35 	[align_and_merge] 	restriction enzyme = DpnII
INFO 	2016-06-02 19:14:35 	[align_and_merge] 	read length = 75
INFO 	2016-06-02 19:14:35 	[align_and_merge] 	genome reference FASTA file found at /users/GR/mb/jquilez/assemblies/homo_sapiens/hg38_mmtv/ucsc/hg38_mmtv_chr1-22XYM.fa
INFO 	2016-06-02 19:14:35 	[align_and_merge] 	mapping, processing reads according to restriction enzyme fragments and merging aligments for read1 and read2...
INFO 	2016-06-03 01:53:41 	[align_and_merge] 	output saved in /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/logs/hg38_mmtv/dc3a1e069_51720e9cf_align_and_merge_paired_end.log
TIME 	2016-06-03 01:56:27 	[align_and_merge] 	step time for completion (seconds) = 24112

INFO 	2016-06-03 01:56:45 	[post_mapping_statistics] 	generating post mapping descriptive statistics plots...
INFO 	2016-06-03 02:28:36 	[post_mapping_statistics] 	fraction of reads mapped read1 = 1.02079243847
INFO 	2016-06-03 02:28:36 	[post_mapping_statistics] 	fraction of reads mapped read2 = 0.918149141956
INFO 	2016-06-03 02:28:36 	[post_mapping_statistics] 	number of pairs in which both read1 and read2 are mapped = 83307066
INFO 	2016-06-03 02:28:36 	[post_mapping_statistics] 	counts-to-distance slope = -1.19970345217
TIME 	2016-06-03 02:28:55 	[post_mapping_statistics] 	step time for completion (seconds) = 1930

INFO 	2016-06-03 02:29:14 	[reads_filtering] 	filtering reads based on multiple quality parameters...
INFO 	2016-06-03 02:29:14 	[reads_filtering] 	filtered reads to be used for subsequent analyses are at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/results/hg38_mmtv/filtered_reads
INFO 	2016-06-03 02:29:14 	[reads_filtering] 	excluded reads due to dangling ends are at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/results/hg38_mmtv/excluded_reads/dangling_ends
INFO 	2016-06-03 02:29:14 	[reads_filtering] 	excluded reads due to self circle are at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/results/hg38_mmtv/excluded_reads/self_circle
INFO 	2016-06-03 02:29:14 	[reads_filtering] 	summary of excluded reads at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/results/hg38_mmtv/excluded_reads/summary_excluded_per_filter
INFO 	2016-06-03 02:47:00 	[reads_filtering] 	numbers and fractions of filtered and excluded reads added to the metadata
TIME 	2016-06-03 02:48:41 	[reads_filtering] 	step time for completion (seconds) = 1184

INFO 	2016-06-03 02:48:43 	[post_filtering_statistics] 	generating post filtering descriptive statistics plots... saved at /users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/plots/hg38_mmtv/post_filtering_statistics:
INFO 	2016-06-03 02:48:43 	[post_filtering_statistics] 	- filtered reads: sequencing coverage along chromosomes, coverage values and interaction matrix
INFO 	2016-06-03 02:48:43 	[post_filtering_statistics] 	- dangling ends: sequencing coverage along chromosomes and coverage values
INFO 	2016-06-03 02:48:43 	[post_filtering_statistics] 	- self-circle ends: sequencing coverage along chromosomes and coverage values
TIME 	2016-06-03 03:06:18 	[post_filtering_statistics] 	step time for completion (seconds) = 1055

INFO 	2016-06-03 03:06:31 	[map_to_bam] 	converting MAP to BAM
[bam_sort_core] merging from 62 files...
TIME 	2016-06-03 04:29:53 	[map_to_bam] 	step time for completion (seconds) = 5002

INFO 	2016-06-03 04:30:09 	[downstream_bam] 	perform several downstream analyses
INFO 	2016-06-03 10:22:31 	[downstream_bam] 	number of TADs = 2911
TIME 	2016-06-03 10:22:55 	[downstream_bam] 	step time for completion (seconds) = 21166

INFO 	2016-06-03 10:22:57 	[clean_up] 	deleting the following intermediate files/directories:
INFO 	2016-06-03 10:22:57 	[clean_up] 	/users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/fastqs_processed
INFO 	2016-06-03 10:22:57 	[clean_up] 	/users/project/4DGenome_no_backup/data/hic/samples/dc3a1e069_51720e9cf/mapped_reads
TIME 	2016-06-03 10:22:58 	[clean_up] 	step time for completion (seconds) = 1


INFO 	2016-06-03 10:23:01 	[pipeline] 	completed successfully
TIME 	2016-06-03 10:23:01 	[pipeline] 	total time for completion (seconds) = 58949

